# This is a basic workflow to help you get started with Actions

name: Release

on:

  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
